name: tsdev
channels:
  - anaconda
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - jupyterlab
  - pandas
  - numpy
  - ipywidgets
  - plotly
  - pip
  - pip:
      - tensorflow

